enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Spotify]
enabled = false
uptodown-dlurl = "https://spotify.en.uptodown.com/android"

[Reddit]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
arch = "both"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
build-mode = "both"
arch = "both"

#[Twitter]
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
#apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
#apkmirror-dpi = "120-640dpi"

[YouTube]
build-mode = "both"
excluded-patches = ""
included-patches = ""
version = "auto"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

#[Twitch]
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"
#apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"

#[Tiktok]
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
#apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
#arch = "both"

#[Instagram]
#apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
#arch = "arm64-v8a"

#[Duolingo]
#apkmirror-dlurl = "https://apkmirror.com/apk/duolingo/duolingo-duolingo/"
#included-patches = "'Disable ads'"
#exclusive-patches = true
#arch = "all"
#apkmirror-dpi = "120-640dpi"

[Yuka]
apkmirror-dlurl = "https://apkmirror.com/apk/yuka-apps/yuka-food-cosmetic-scan/"

[GooglePhotos]
version = "auto"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos/"
included-patches = "'com.google.android.apps.photos.nexus_preload' 'com.google.android.apps.photos.NEXUS_PRELOAD' 'com.google.android.feature.PIXEL_2021_EXPERIENCE' 'com.google.android.feature.PIXEL_2022_EXPERIENCE'"
arch = "both"
build-mode = "both"
